/*
========================================================================================
    PREPARE_MULTIQC_CONFIG Module
========================================================================================
    Generates MultiQC configuration file with sample renaming and report header info
*/

process PREPARE_MULTIQC_CONFIG {
    label 'process_single'
    executor 'local'

    input:
    val(sample_info)      // List of maps with: fli, sample_name, species
    val(project_name)
    val(application)

    output:
    path("multiqc_config.yaml"), emit: config

    script:
    // Build sample rename entries
    def rename_entries = sample_info.collect { info ->
        def display_name = info.sample_name ?: info.fli
        if (info.species) {
            display_name = "${info.sample_name ?: info.fli} (${info.species})"
        }
        "    - ['${info.fli}', '${display_name}']"
    }.join('\n')

    // Build header info
    def header_items = []
    if (project_name) {
        header_items << "    - Project: '${project_name}'"
    }
    if (application) {
        header_items << "    - Application: '${application}'"
    }
    def header_section = header_items ? "report_header_info:\n${header_items.join('\n')}" : ""

    """
    cat <<EOF > multiqc_config.yaml
# MultiQC configuration generated by BasicQC pipeline
title: "${project_name ?: 'BasicQC'} Report"
subtitle: "${application ?: 'Quality Control Analysis'}"

${header_section}

# Sample name cleaning and renaming
sample_names_replace_regex: true
sample_names_replace:
${rename_entries}

# Clean up common suffixes
extra_fn_clean_exts:
    - '.subsampled'
    - '_1'
    - '_2'
    - '.fastq.gz'
    - '.fastq'
    - '.fq.gz'
    - '.fq'
    - '.kraken2.report'
    - '.kraken2.output'
    - '_fastqc'

# Table columns configuration
table_columns_visible:
    FastQC:
        percent_duplicates: True
        percent_gc: True
        avg_sequence_length: True
        percent_fails: False
        total_sequences: True

# General settings
log_filesize_limit: 2000000000
EOF
    """
}
